name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install zip tool
        run: sudo apt-get install zip -y
        
      - name: Create Zip file for Lambda function
        run: zip -r code.zip .
        
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:424056758898:function:TestFunction \
            --zip-file fileb://code.zip
            
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
